export enum UserErrors {
  USER_ERROR_EMAIL_EXISTS = 'USER_ERROR_EMAIL_EXISTS',
  USER_ERROR_ALIAS_EXISTS = 'USER_ERROR_ALIAS_EXISTS',
  USER_ERROR_ALREADY_REGISTERED_WITH_GOOGLE = 'USER_ERROR_ALREADY_REGISTERED_WITH_GOOGLE',
  USER_SHOULD_AUTHENTICATE_WITH_GOOGLE = 'USER_SHOULD_AUTHENTICATE_WITH_GOOGLE',
}
